# Generated by Django 4.0.2 on 2022-02-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apellidos', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('hobbies', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('tipo_id', models.CharField(choices=[('dni', 'dni'), ('cc', 'cédula'), ('pas', 'pasaporte'), ('otro', 'otro')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.roles')),
            ],
        ),
    ]
