# Generated by Django 4.0.2 on 2022-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_dni',
            field=models.CharField(default='dni', max_length=10),
        ),
    ]
