# Generated by Django 4.0.2 on 2022-02-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_usuario_tipo_id_usuario_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_dni',
            field=models.CharField(default='dni', max_length=20),
        ),
    ]
