# Generated by Django 4.0.2 on 2022-02-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_usuario_tipo_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='hobbies',
            field=models.TextField(max_length=200),
        ),
    ]
